# server configuration
server:
  port: 9191

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/messagegateway
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host: localhost
  protocol: http

callbackconfig:
  host: 0.0.0.0
  protocol: http
  port: 5000

application:
  version: 1.0.0

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true

providerSource:
  fromDatabase: disabled
  fromyml: enabled

providerKeys:
  telerivetApiKey: eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl
  telerivetProjectId: PJ5ff552ce01d2978c

logging:
  level:
    ROOT: INFO
